
计算图（computational graph）

正向传播（forward propagation)

反向传播（backward propagation):沿着与正方向相反的方向，乘上局部导数

链式法则（chain rule）
- 假设某个函数由复合函数构成， 则复合函数的导数可以用构成复合函数的各个函数的导数的乘积组成

比如:

$z=(x+y)^2$  

$z=t^2$ 

$t=x+y$ 

$$
\frac{\partial z}{\partial x}= \frac{\partial z}{\partial t}\frac{\partial t}{\partial x}=2t*1=2(x+y)
$$

- 反向传播是基于链式法则的
- 加法节点的反向传播：将上游的值原封不动的输出到下游,因为对加法公式中的变量求局部导数时始终为1,反向传播时乘上局部导数，值不变
- 乘法节点的反向传播：将上游的值乘以正向传播时输入信号的翻转值后传递给下游,以z=xy，对x,y分别求导，再乘以反向传播时的输入信号为例就好理解了，区别于加法节点的反向传播不需要知道正向传播时的输入信号，乘法的反向传播需要正向传播时的输入信号值;因此实现乘法节点的反向传播时，需要保存正向传播时的输入信号


In [16]:
# 计算图在神经网络中应用
import numpy as np
x=np.array([[1.0,-0.5],[-2.0,3.0]])
print(x)
mask=(x<=0)
print(mask)
out=x.copy()
print("=====befor======")
print(out)
out[mask]=0
print("=====after======")
print(out)




print("=======")
index= out[[[False,  True], [True, False]]]
print(index)
index=0
print(index)




[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]
=====befor======
[[ 1.  -0.5]
 [-2.   3. ]]
=====after======
[[1. 0.]
 [0. 3.]]
[0. 0.]
0
